import './label.js';

/**
 * Testing custom element generation patterns
 */
export default class WC3ways extends HTMLElement {
  /**
   * Attach
   */
  connectedCallback() {
    this.innerHTML = /*html*/ `
      <h1>Three ways to generate CustomElements</h1>
      <!-- ① Declarative tag writing pattern -->
      <wc-label label="① hello"></wc-label>
    `;

    // ② Generated by new operator
    const Label = window.customElements.get('wc-label');
    const labelElmA = new Label('② hello');
    this.appendChild(labelElmA);

    // ③ Generated by DOM API
    const labelElmB = document.createElement('wc-label');
    labelElmB.label = '③ hello';
    this.appendChild(labelElmB);
  }
}

// Register custom element
window.customElements.define('wc-3ways', WC3ways);
